# Nombre del flujo de trabajo
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Suscripción de Azure 1 (8d0335de-edca-4d9d-a54d-581aa8c5a17e)'
    appType: 'webApp'
    WebAppName: 'alexisfabricio'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
name: CompilacionWeb

# Gatillo: Se ejecutará cuando haya cambios en la rama 'main'
trigger:
- main

# Definición de los pasos
jobs:
- job: Compilacion
  displayName: Compilación y Empaquetado del Sitio Web
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: |
      echo Compilando el sitio web...
      # Agregar aquí los comandos para compilar el sitio web si es necesario
    displayName: Compilación

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/sitio-web.zip'
      replaceExistingArchive: true
    displayName: Empaquetado

  - task: PublishPipelineArtifact@1
    inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/sitio-web.zip'
        artifact: 'sitio-web-artifact'


